name: lint

on:
  push:
    branches: [main]

  pull_request:
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Setting Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3

        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies

        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing The Code With pylint
        run: pylint $(git ls-files '*.py')